name: Deploy Web
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go build -o build/game.wasm
        env:
          GOOS: js
          GOARCH: wasm
      - run: ls -la build      
      # used to pass build artifacts between jobs build and deploy    
      - uses: actions/upload-artifact@master
        with:
          name: page
          path: build
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.23'
      - run: mkdir -p web
      # Create index.html dynamically (needs to be provided, else we get 404
      # for the github page)
      - run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <title>GoBoomah</title>
          </head>
          <body>
              <h1>GoBoomah WebAssembly (WASM) App</h1>
              <script src="wasm_exec.js"></script>
              <script>
                  const go = new Go();
                  WebAssembly.instantiateStreaming(fetch("game.wasm"), go.importObject).then((result) => {
                      go.run(result.instance);
                  });
              </script>
          </body>
          </html>' > web/index.html
      - run: cp -v $(go env GOROOT)/misc/wasm/wasm_exec.js web/
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: web
      - id: deployment
        uses: actions/deploy-pages@main
