name: Deploy Web
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go build -o web/game.wasm
        env:
          GOOS: js
          GOARCH: wasm
      - run: ls -la web      
      # used to pass build artifacts between jobs build and deploy    
      - uses: actions/upload-artifact@master
        with:
          name: page
          path: web
          if-no-files-found: error

# How to run ebitengine games on wasm:
# https://ebitengine.org/en/documents/webassembly.html
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.23'
      - run: ls -lha web/
      - run: cp -v $(go env GOROOT)/misc/wasm/wasm_exec.js web/
      - run: ls -lha web/ 
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: web
      - id: deployment
        uses: actions/deploy-pages@main
